#!/usr/bin/env python3
"""
Generate C header file with PCM audio data array from WAV file.
Usage: python3 generate_pcm_header.py input.wav output.h
"""

import sys
import wave
import struct

def generate_pcm_header(wav_path, header_path):
    """Convert WAV file to C header with PCM data array."""
    
    # Read WAV file
    with wave.open(wav_path, 'rb') as wav:
        # Verify format
        channels = wav.getnchannels()
        sample_width = wav.getsampwidth()
        framerate = wav.getframerate()
        n_frames = wav.getnframes()
        
        if channels != 1:
            print(f"ERROR: Expected mono (1 channel), got {channels}", file=sys.stderr)
            sys.exit(1)
        
        if sample_width != 2:
            print(f"ERROR: Expected 16-bit (2 bytes), got {sample_width} bytes", file=sys.stderr)
            sys.exit(1)
        
        # Read all frames as raw bytes
        raw_data = wav.readframes(n_frames)
    
    # Convert bytes to int16 samples
    samples = struct.unpack(f'<{n_frames}h', raw_data)
    
    # Generate C header
    with open(header_path, 'w') as f:
        f.write(f"""// Auto-generated PCM audio data from {wav_path}
// DO NOT EDIT - Generated by generate_pcm_header.py

#ifndef ENGINE_PCM_H
#define ENGINE_PCM_H

#include <stdint.h>

// Audio metadata
#define ENGINE_PCM_SAMPLE_RATE {framerate}
#define ENGINE_PCM_LENGTH {n_frames}
#define ENGINE_PCM_DURATION_MS {int(n_frames / framerate * 1000)}

// PCM data array (16-bit signed, mono)
const int16_t ENGINE_PCM_DATA[{n_frames}] = {{
""")
        
        # Write samples in rows of 12 for readability
        for i in range(0, len(samples), 12):
            row = samples[i:i+12]
            f.write("    ")
            f.write(", ".join(f"{s:6d}" for s in row))
            if i + 12 < len(samples):
                f.write(",\n")
            else:
                f.write("\n")
        
        f.write("""};

#endif // ENGINE_PCM_H
""")
    
    # Print summary
    duration_s = n_frames / framerate
    size_kb = len(samples) * 2 / 1024
    print(f"  ✓ Generated {header_path}")
    print(f"    Sample rate: {framerate} Hz")
    print(f"    Samples: {n_frames} ({duration_s:.2f}s)")
    print(f"    Size: {size_kb:.1f} KB")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 generate_pcm_header.py input.wav output.h")
        sys.exit(1)
    
    generate_pcm_header(sys.argv[1], sys.argv[2])
