#!/usr/bin/env python3
"""Generate C header from PCM WAV file (for raw/unfiltered version)"""

import wave
import sys

def generate_header(wav_file, header_file):
    with wave.open(wav_file, 'rb') as wav:
        sample_width = wav.getsampwidth()
        channels = wav.getnchannels()
        sample_rate = wav.getframerate()
        num_samples = wav.getnframes()
        
        if sample_width != 2:
            print(f"ERROR: Expected 16-bit samples, got {sample_width*8}-bit")
            return False
        
        if channels != 1:
            print(f"ERROR: Expected mono, got {channels} channels")
            return False
        
        # Read all samples
        frames = wav.readframes(num_samples)
        samples = []
        for i in range(0, len(frames), 2):
            sample = int.from_bytes(frames[i:i+2], byteorder='little', signed=True)
            samples.append(sample)
        
        # Generate header
        with open(header_file, 'w') as h:
            h.write("// Auto-generated PCM audio data from engine_raw.wav\n")
            h.write("// DO NOT EDIT - Generated by generate_pcm_header_raw.py\n\n")
            h.write("#ifndef ENGINE_PCM_RAW_H\n")
            h.write("#define ENGINE_PCM_RAW_H\n\n")
            h.write("#include <stdint.h>\n\n")
            
            h.write("// Audio metadata\n")
            h.write(f"#define ENGINE_PCM_RAW_SAMPLE_RATE {sample_rate}\n")
            h.write(f"#define ENGINE_PCM_RAW_LENGTH {num_samples}\n")
            h.write(f"#define ENGINE_PCM_RAW_DURATION_MS {int(num_samples * 1000 / sample_rate)}\n\n")
            
            h.write("// PCM data array (16-bit signed, mono)\n")
            h.write(f"const int16_t ENGINE_PCM_RAW_DATA[{num_samples}] = {{\n")
            
            # Write samples in chunks of 12 per line
            for i, sample in enumerate(samples):
                if i % 12 == 0:
                    h.write("  ")
                h.write(f"{sample:7d},")
                if (i + 1) % 12 == 0:
                    h.write("\n")
            
            if len(samples) % 12 != 0:
                h.write("\n")
            
            h.write("};\n\n")
            h.write("#endif // ENGINE_PCM_RAW_H\n")
        
        duration_sec = num_samples / sample_rate
        print(f"✓ Generated {header_file}")
        print(f"  Sample rate: {sample_rate} Hz")
        print(f"  Samples: {num_samples} ({duration_sec:.2f}s)")
        print(f"  Size: {len(frames) / 1024:.1f} KB")
        
        return True

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: generate_pcm_header_raw.py input.wav output.h")
        sys.exit(1)
    
    success = generate_header(sys.argv[1], sys.argv[2])
    sys.exit(0 if success else 1)
